files:
  calm:
    loop: true
    src: music/music.mp3
    fadeInTime: 2
    fadeOutTime: 2
    volume: 0.3
  battle:
    loop: true
    src: music/battle.mp3
  click:
    src: audio/click.ogg
  game_start:
    volume: 0.9
    src: audio/game_start.ogg
  failure:
    src: audio/failure.ogg
  success:
    src: audio/success.wav
  letter-a:
    src: audio/letter-1.wav
  letter-b:
    src: audio/letter-2.wav
  letter-c:
    src: audio/letter-3.wav
  letter-d:
    src: audio/letter-4.wav
  letter-e:
    src: audio/letter-5.wav
  letter-f:
    src: audio/letter-6.wav
  letter-g:
    src: audio/letter-7.wav
  letter-h:
    src: audio/letter-1.wav
  letter-i:
    src: audio/letter-2.wav
  letter-j:
    src: audio/letter-3.wav
  letter-k:
    src: audio/letter-4.wav
  letter-l:
    src: audio/letter-5.wav
  letter-m:
    src: audio/letter-6.wav
  letter-n:
    src: audio/letter-7.wav
  letter-o:
    src: audio/letter-1.wav
  letter-p:
    src: audio/letter-2.wav
  letter-q:
    src: audio/letter-3.wav
  letter-r:
    src: audio/letter-4.wav
  letter-s:
    src: audio/letter-5.wav
  letter-t:
    src: audio/letter-6.wav
  letter-u:
    src: audio/letter-7.wav
  letter-v:
    src: audio/letter-1.wav
  letter-w:
    src: audio/letter-2.wav
  letter-x:
    src: audio/letter-3.wav
  letter-y:
    src: audio/letter-4.wav
  letter-z:
    src: audio/letter-5.wav

options:
  # defaultMusic: calm
  volume: 0.5
  musicFadeInTime: 0.5
  musicFadeInDelay: 0.5
  musicFadeOutTime: 0.5

audioTriggers: {}

dialogAudio:
  defaultAudio:
    soundPerLetter:
      prefix: letter-
      volume: 0.2
  characterAudio:
    helper:
      soundOnNewLine: click
