---
gameTitle: Narrat Game Example
saveFileName: Narrat Empty
images: {}
dialogPanel:
  textSpeed: 30
  animateText: true
  timeBetweenLines: 100
  overlayMode: true
  rightOffset: 100
  bottomOffset: 50
  width: 475
  height: 680
layout:
  backgrounds:
    width: 1280
    height: 720
  dialogBottomPadding: 70
  mobileDialogHeightPercentage: 60
  verticalLayoutThreshold: 600
  portraits:
    width: 180
    height: 350
notifications:
  timeOnScreen: 2.5
  alsoPrintInDialogue: true
hudStats: {}
interactionTags:
  default:
    onlyInteractOutsideOfScripts: true
menuButtons: {}
saves:
  mode: manual
  slots: 10
